# While loop exercises

# 1. Create a while loop of 20 iterations that prints "image1.png" for the first 10 iterations, and "image2.png" for the next 10 iterations.
iteration = 0

while iteration < 20:
    if iteration <10:    
        print('image1.png')
    elif iteration <20:
        print('image2.png')
    iteration = iteration + 1

# 2. Create a while loop that shows an image until the participant makes a response of 1 or 2. 
# Run it a few times to make sure it works the way you expect.

# code according to tutorial 
response = False
iteration = 0

while not response:
    iteration = iteration + 1
    print("image.png for %i iterations" %iteration)
    
    if response == 1 or response == 2:
        response = True
        
# SUBMITTED FOR ASSIGNMENT = edited code using class demo:      
import random 
response = '' # response will be generated by randint for testing
image_looping = True # show an image until response

while image_looping: # keep showing image loop
    print("Showing an image here") # image presentation
    response = random.randint(0,10) # simulate response by generating a number
    print("Response generated was %i for image shown" %response) # print to see if code correctly checks for response that is 1 or 2
    if response == 1 or response == 2: # if generated response is 1 or 2
        image_looping = False # stop looping

# 3. Create a failsafe that terminates the previous while loop after 5 iterations if one of the valid responses (1,2) have not been made in that time.

# code according to tutorial 
response = False
iteration = 0
failsafe = 0

while not response:
    iteration = iteration + 1
    print("image.png for %i iterations" %iteration)
    failsafe = failsafe + 1
    if response == 1 or response == 2 or failsafe == 5:
        response = True
        
# SUBMITTED FOR ASSIGNMENT = edited code using class demo:     
import random 
response = '' # response will be generated by randint for testing
image_looping = True # show an image until response
failsafe = 0 # count while loop iterations

while image_looping: # keep showing image loop
    print("Showing an image here") # image presentation
    response = random.randint(0,10) # simulate response by generating a number
    print("Response generated was %i for image shown" %response) # print to see if code correctly checks for response that is 1 or 2
    failsafe = failsafe + 1 # add 1 count after every while loop iteration
    if response == 1 or response == 2 or failsafe == 5: # if generated response is 1 or 2 or 5 loop iterations without valid 1 or 2 response
        image_looping = False # stop looping


        

    
    
    
        
        